### ISSUE TITLE
Requests for other cities

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#10]
This is a place to record requests to do other cities with names so we can elicit feedback and provide heads-up when results are released.

- [x] Coventry, Adam Tranter (email to Robin)
- [x] Nottingham ([Twitter](https://twitter.com/markjd84/status/1258429046800764929) and [Twitter](https://twitter.com/rwilloe/status/1258414614011875328))
- [x] Southampton, Dr Ben Anderson 
- [x] Portsmouth via [Twitter](https://twitter.com/TallestTim/status/1258416247672311811)
- [x] Norwich via [Twitter](https://twitter.com/24bitwarrior/status/1259403181718716418)
- [x] Derby (see below)
- [x] Greater Manchester (see below)

**Comment by dataknut** [comment]
Southampton pls

**Comment by mem48** [comment]
Huddersfield!

**Comment by jf1** [comment]
All of (Greater) Manchester please, and if it's straightforward further instances for each LA would be welcome.

**Comment by smoky67** [comment]
Derby please. ian.dent@derbycyclinggroup.org.uk Have previously done some work with the PCT code and data so will try myself in the meantime! Thanks.

**Comment by Robinlovelace** [comment]
Heads-up @smoky67 preliminary results here: https://cyipt.github.io/popupCycleways/v1/norfolk/

I will email the contact sent. Feedback welcome.

I've contacted other people who made requests so closing for now.
