### ISSUE TITLE
Manual changes

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#11]
Until we automate the process I'm opening-up this issue as a place to track additional changes that have been requested:

- [ ] remove the 4x A34 entries from the top of the list as all these sections of this road already have cycle provision (Jonathan)

**Comment by jf1** [comment]
This looks implemented in v2 - thanks @Robinlovelace,. I've since realised that A34 has been used on two parallel roads over the years - we now have no infra on one and good infra on (most of) the other, so it still makes sense to suppress the A34 for now (which helps promote the nearby A6 as well as other useful routes).

**Comment by Robinlovelace** [comment]
Thanks @jf1. It raises a question: should roads with *any* cycle infra be omitted from the results? Cycle campaigners such as you and @mvl22 seem to think so but I'm not sure for a few reasons, not least because cycle infrastructure cannot be assumed to be adequate or wide enough or provide enough space for walking and cycling.

Taking the point on-board my suggested solution is that roads can be highlighted, but not as 'top' roads in the darker blue shade. Sound reasonable?

**Comment by mvl22** [comment]
The criteria should ideally be where it is of reasonable quality.

In the Hills Road Bridge case, there are 2.1m cycleways, a width which is in OSM (as will be the case with anything of good quality usually, as people will make the effort to flag it as such). Where there are poor-quality cycle lanes that are very narrow, e.g. 1.2m or worse, then that would not really count as real cycle infrastructure.

I agree this is difficult to do without more extensive analysis.

**Comment by Robinlovelace** [comment]
Given that there is no known way of reliably assessing width and quality nationwide my interim solution sounds 'good enough for now safe enough to try'.

**Comment by jf1** [comment]
I'm not aware of anyone adding OSM widths for GM's better cycleways, and even if it this has been done I'm not confident that there is or will be a way to compute what you're after.

I'm thinking beyond widths - eg we've had an A road's inside lanes coned off but the anti-pedestrian guardrails remain so it doesn't yet help walking, and the coned area has not been designed to cycle in or out of, but I still see it as progress as we can now have dialogue about those two issues.

Have you considered whether any coned-off areas would be used exclusively for cycling, or more likely for both walking and cycling? I'm expecting the latter and think current efforts should focus on the general principle of transferring space from motorised to human-powered travel, with the new priorities of access to healthcare, retail and public transport, on a more local scale than people's pre-Covid travel patterns.

If people will be encouraged to walk in pre-existing or temporary cycleways then perhaps the simplest calculation is: does `total highway width from OS` - `minimum for 2x motor lanes` leave `> preset amount` but as we're all aware the kerblines, drainage etc are crucial and LAs are very stretched at the moment so it may be simpler to just present more results per area to enable people with local knowledge to filter out any unsuitable recommendations.

**Comment by mvl22** [comment]
> OSM widths for GM's better cycleways

Cycleway widths should always be added to OSM. They enable routing engines that actually care about level of service to determine if this is any good.

Attributes that form best practice for cycleway tagging are:

- width/est_width
- surface=...
- lit=yes/no
- segregated=yes/no
- foot=yes/no
- lcn=yes (or ideally create relation)

I would strongly recommend adding these to all cycleways - they will improve routing quality.
