### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#13]
Making wider point that digital tools can support effective decision-making, as illustrated in image below.

![image](https://user-images.githubusercontent.com/1825120/81451234-ed82d200-917b-11ea-977d-fff1665378c5.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/81471440-0aa1ba00-91e9-11ea-8e6e-dd9f7669bf98.png)

**Comment by mem48** [comment]
Comments on the article

kkm is a horrible unit us either Mm or km (thousands)

It is not clear why you give such prominance to hospital locations, I think your argument is that people need to get to the hospitals. But that is not made clear, you talk about "key workers" but that is a UK term and may not translate. Also you don't have data on where doctors and nurses live, nor do you subset to only commuters going to the nearest LSOA. I think you need ot be clear on what the question your trying to answer is. Perhaps make it more general and less focues on hosptials.

I don't think the admin boundary / buffer section is very helpful. Either you are doing an analysis of the adminstative region or your doing something based on travel to hospitals, which is it? Then choose that method. It would also free up words to say more in other areas.

I think you need a long section of discussion of the resutls, strengths and weaknesses of the method etc. What boaut where there is not a spare lane, are the criteria you used appropriate. How does this "pop-up" appraoche differ from the normal CyIPT method. e.g. are the "pop-roads" places where something needed doing in any case, or are we redriect focus to second rate options?

**Comment by Robinlovelace** [comment]
Thanks @mem48 I realise now that the results were actually km (m * 1000) so an easy fix.

The hospitals are an example of a key destination. They could be anything. Hopefully the reader will see that. We're already at 1000 words, I take you points, but unless you have specific suggestions (ideally a PR implementing them) we'll have to leave it to the reviewers.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/81581619-e2f85080-93a6-11ea-9bbe-c11ce3ea57e2.png)

**Comment by mvl22** [comment]
I must admit I've been finding it rather odd just seeing hospitals there. If the intention is to have key destinations, main shopping areas seem to me odd not to show.

**Comment by Robinlovelace** [comment]
Feel free to open an issue and demonstrate a way of getting a consistent national dataset of shopping areas. There is a workplace element.

**Comment by mvl22** [comment]
Refs https://github.com/cyipt/acton/issues/5
