### ISSUE TITLE
Website link has moved

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#18]
Heads-up @mvl22 currently people going here are seeing a 404: https://cyipt.github.io/tempCycleways/

Easiest solution: redirect to https://cyipt.github.io/popupCycleways/

Any ideas how to do that? Or we could re-create the old site via GH pages.

**Comment by mvl22** [comment]
A page containing a crappy meta-redirect is probably the only solution given the restrictions imposed by github.io hosting (i.e. no server-side).

<head>
    <meta http-equiv="refresh" content="4; URL='https://cyipt.github.io/popupCycleways/'" /> 
</head>
<body>
</body>

**Comment by jf1** [comment]
AIUI now that the renaming has been done you'll need to create a new tempcycleways project with a .io page that redirects people to the popupcycleways' .io page.

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 I've added the redirect, not working yet... https://github.com/cyipt/tempCycleways/blob/gh-pages/index.html

Assume we'll need to do that for all relevant pages, but it's OK because the landing page was the only one we used...

**Comment by Robinlovelace** [comment]
https://cyipt.github.io/tempCycleways/
