### ISSUE TITLE
Develop function to identify (and remove) duplicate dual carriageways

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#21]
There are pros (especially when there is a physical barrier) and cons of showing separate lanes. My thinking at the moment is that the -s outweigh the +s. Proposing a method to remove duplicates that are only meters apart. Example from Bristol below. Would be good to update the attributes in the remaining road. Thoughts @mem48 ? Any other thoughts on this welcome.

![image](https://user-images.githubusercontent.com/1825120/81834041-5ed5d280-9538-11ea-853a-c0dc47e52585.png)

**Comment by mvl22** [comment]
Didn't CyIPT do some pre-processing in this regard?

**Comment by mem48** [comment]
CYIPT is dual carriageway aware, but doesn't try and remove them. I think in the long term the best solution is to redo the routing, and not assume A to B is the same as B to A.this would properly evaluate all one way roads including dual carriageway and we can handle the increase data volume thanks to better code.
