### ISSUE TITLE
UI ideally needs hash added

### ISSUE THREAD

**Issue by mvl22** [cyipt/popupCycleways#48]
I recommend ensuring the UI sets the Leaflet hash, using:

https://github.com/mlevans/leaflet-hash

as otherwise the map position is not persistent when a link is circulated.

**Comment by Robinlovelace** [comment]
Agreed. There's no simple solution because we're generating the HTML/.js code with R, happy to consider for the next version.

**Comment by Robinlovelace** [comment]
Interestingly seems it has been done but this implementation is not well maintained: https://bhaskarvk.github.io/leaflet.extras/

**Comment by mvl22** [comment]
> There's no simple solution because we're generating the HTML/.js code with R

Yeah, I realised that. Though it was probably worth flagging so it's kept in mind, and in case there's an R version or some way to attach bits of HTML (to load the plugin and add that one-liner to the JS) manually.

**Comment by layik** [comment]
This where I should be contributing! Sorry.

**Comment by Robinlovelace** [comment]
Ideas welcome, probably for the next round. Easy to add for geoplumberSaferActive?

**Comment by mvl22** [comment]
Have you tried this package, which contains Leaflet.hash, which is all you need to enable?

https://cran.r-project.org/web/packages/leaflet.extras/leaflet.extras.pdf

**Comment by Robinlovelace** [comment]
No, but I see this project as out-of-scope for the current project, development time on which ends next week. Happy to re-open this issue later down the line. ATM I think the best way forward is for the data to be provided other web apps that do have hashing such as widenmypath (on that note I know I still need to send you the top routes).
