### ISSUE TITLE
Turn off or reduce prominance of other layers

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#55]
To make the maps less cluttered, as illustrated below.

![image](https://user-images.githubusercontent.com/1825120/83228927-f49b6f80-a17e-11ea-8ecc-1f7b2ef197f4.png)

Also I think the blue lines should be on top of all other lines in the map.

**Comment by mvl22** [comment]
Does "Top route" mean "Top recommended route"?

**Comment by Robinlovelace** [comment]
It means the top n routes highlighted in blue. The value of n depends on the size of the region.

**Comment by jf1** [comment]
So they're "Top value" routes?

And what does "Key network" mean - is this a network in its own right, or does it and the other layers make a network?

**Comment by Robinlovelace** [comment]
See description here: https://cyipt.github.io/popupCycleways/v0.3/

**Comment by mvl22** [comment]
I suggest renaming the label “Key cycle routes” to “Ideal cycle network”, having now read the documentation of what it is.

**Comment by Robinlovelace** [comment]
> I suggest renaming the label “Key cycle routes” to “Ideal cycle network”, having now read the documentation of what it is.

Good suggestion but that's too strong. How about 'Cohesive network'?

**Comment by mvl22** [comment]
> Good suggestion but that's too strong. How about 'Cohesive network'?

Something like that, certainly. The problem is that "Key cycle routes" implies that it's what is being suggested as feasible. "Ideal" gives a much stronger sense that it's the ideal, but we all know that ideals cannot always come to fruition. "Cohesive" is probably somewhere between those two.
