### ISSUE TITLE
Add links to map

### ISSUE THREAD

**Issue by mem48** [cyipt/popupCycleways#70]
It would be nice if you could use the map on the main page to go to each regions map. Shoudl just be a simple case of adding a url column to the dataset.

**Comment by Robinlovelace** [comment]
You can already: have you tried search for a region and clicking on the URL in the table? Open to ideas of how to make it easier to get to the regions.

**Comment by mem48** [comment]
I can click on the links in the table, but I don't see any links on the map

**Comment by Robinlovelace** [comment]
Ah yes. I would need to re-build the map with leaflet commands for that. Worth doing, not a priority. Let me know if you want to give it a bash, here is the code: https://github.com/cyipt/popupCycleways/blob/master/code/index.Rmd#L141
