### ISSUE TITLE
Rename and re-order legend entries

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#76]
As discussed today, so that they reflect the time-scales on which the results are relevant:

```
Existing cycleway (now)
Top ranked new cycleways (near term)
Cohesive network (long term)
```

**Comment by mvl22** [comment]
These are good.

**Comment by Robinlovelace** [comment]
Before: 

![image](https://user-images.githubusercontent.com/1825120/83695240-92fd5a00-a5f1-11ea-9e0a-c2e7a08d1dd5.png)


After:

![image](https://user-images.githubusercontent.com/1825120/83695340-c0e29e80-a5f1-11ea-827e-69dbf0a5a3df.png)


(showing bug with A10...)
