### ISSUE TITLE
Host results at permanent address

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#80]
Without a redirect. You up for that @mvl22 ? We can put it in place now with /v1 mapped to /rapid.

**Comment by mvl22** [comment]
I'm not sure what you mean?

Did you mean putting the results down automatically to the main server? I can set that up, yes.

**Comment by Robinlovelace** [comment]
Thanks Martin, I'll give you a call to confirm.

**Comment by mvl22** [comment]
Done.

https://www.cyipt.bike/rapid/

now tracks on a five-minutely basis against branch `gh-pages`.

https://github.com/cyipt/popupCycleways/tree/gh-pages/

**Comment by Robinlovelace** [comment]
Great to see, many thanks for rapid work!
