### ISSUE TITLE
Suggestions for the map viewer

### ISSUE THREAD

**Issue by jf1** [cyipt/popupCycleways#81]
The grey line for LA Boundary is inconspicuous. #FF00FF would work for me and the only potential clash with tiles is a very small amount (in GM) of #FF00C5 in the PCT ebike scenario.

Basemaps - I expect most users, especially new ones, would find the 'Existing cycle...' layer more useful than the PCT ones, so I'd sort them abc to give...
 Existing cycleways and cycle lanes (nice tiles btw!)
 Grey basemap
 PCT commuting, Government Target
 PCT schools, Government Target
 PCT commuting, Ebikes,
 PCT schools, Go Dutch,
 Satellite image
...and whilst I could understand placing the Satellite image 3rd (with the other 'normal' maps) everything in this list and the others below could be sorted abc, so that's my preference.

I presume it's possible to ensure the 2nd basemap is pre-selected on load - if not could the "Existing" layer have another name, eg "OpenStreetMap existing cycle provision (CyclOSM)" to place it second alphabetically.

It's possible to zoom in too much for all but the Existing and Satellite tiles - should max zoom be limited for the other layers? (iirc it'd need different max_zoom for Grey and PCT)

The 'Existing off road cycleways' data is very prominent and I feel it distracts from the Popup data so I'd prefer this to be disabled on initial view.

That and renaming "Estimated width >10m" to "Width >10m (estimated)" would enable those layers to be sorted by initial visibility then abc, ie:
 Key cycle routes
 Local authority district boundaries
 Existing off road cycleways - or:  Off-road cycleways (existing) so it's just an abc sort
 Spare lane(s)
 Top routes
 Width > 10m (estimated)
...and I'd drop the (estimated) but no biggie there - I imagine that others here are keen to keep it.

Finally, the top-right info box could be more consistent - either show each layer's info only when the layer is visible, or (my preference) just show all layers' info all the time, ideally abc sorted as above.

**Comment by Robinlovelace** [comment]
Do these suggestions apply to the latest results, e.g. here?: https://www.cyipt.bike/rapid/west-yorkshire/

Please be specific and narrow in your suggestions, limited developer bandwidth in short time space as you can imagine!

**Comment by jf1** [comment]
Yes, based on https://www.cyipt.bike/rapid/greater-manchester/m.html to be precise.

I've tried to be as specific as possible. How's this...

Please change basemap names and order to:
Grey basemap
OSM existing cycle provision (CyclOSM)
PCT commuting, Government Target
PCT schools, Government Target
PCT commuting, Ebikes
PCT schools, Go Dutch
Satellite image

For the Grey and PCT basemap layers, please configure their max_zoom levels or reconfigure tile servers, to ensure users don't experience "tiles not available" outputs.

Please change data layer, names, order and initial visibility to:
Key cycle routes	`visible`
Local authority district boundaries	`visible`
Off-road cycleways (existing)	`not-visible`
Roads with spare lane(s)	`not-visible`
Top-potential cycle routes	`not-visible`
Width > 10m (estimated)	`not-visible`

Please change LA boundary colour to #FF00FF

Please make the top-right data-layer info box consistent. Either ensure it always displays only the currently selected layers in the correct sort order, or the easiest option is to always show the same key that includes all available layers.

And if you're not already considering this one - should the Cohesive / Core Network layer be in a more prominent colour than grey?

**Comment by Robinlovelace** [comment]
Very good feedback @jf1 we will try to incorporate these changes in the limited time we have left on the project. Going full speed and #82 is my next priority.

**Comment by Robinlovelace** [comment]
Implementation of your suggestions @jf1, look good to you? Heads-up @joeytalbot, @mvl22 and @mem48 who have also commented on maps.

![image](https://user-images.githubusercontent.com/1825120/83941243-d4ecf280-a7e1-11ea-8fdd-645bcfda4540.png)

**Comment by Robinlovelace** [comment]
See online version here: https://cyipt.github.io/popupCycleways/v1.1/cambridgeshire-and-peterborough/
