### ISSUE TITLE
Inclusion of roads with only 1 lane in either direction but spare space

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#9]

**Comment by Robinlovelace** [comment]
Unused width on the A6 in Pendleton.

**Comment by jf1** [comment]
Should this issue's title be "with **only** 2 lanes but spare space" or similar?

You're welcome to also consider Edge Lane in Trafford - it's mostly 2 lanes (sometimes 3 with a part-time bus / parking lane) and Trafford have listed it as a location for immediate action. NB this is the section east of King's Road (it's 4 lanes to the west and cones have already gone in there).
